# Top menu for Carpentries & Lesson Programs
top:
  - name: The Carpentries
    url: /
    weight: 10
    params:
      active: true
  - name: Data Carpentry
    url: https://dc-new-website.netlify.app/
    weight: 20
  - name: Software Carpentry
    url: https://swc-new-website.netlify.app/
    weight: 30
  - name: Library Carpentry
    url: https://lc-new-website.netlify.app/
    weight: 40
# About page tabbed menu
about:
- name: About us
  pageRef: /about-us
  weight: 10
- name: Impact
  pageRef: /about-us/impact
  weight: 20
- name: Governance
  pageRef: /about-us/governance
  weight: 30
- name: Our team
  pageRef: /about-us/team
  weight: 40
- name: Financials
  pageRef: /about-us/financials
  weight: 50
- name: Contact us
  pageRef: /about-us/contact
  weight: 70
# Workshops page tabbed menu
workshops:
- name: Workshops
  pageRef: /workshops
  weight: 10
- name: Workshops FAQ
  pageRef: /workshops/workshops-faq
  weight: 30
- name: Upcoming workshops
  pageRef: /workshops/upcoming-workshops
  weight: 50
# Host tabbed menu
host:
- name: Host a workshop
  pageRef: /host/host-workshop
  weight: 10
- name: Host a training
  pageRef: /host/host-training
  weight: 20
- name: Pricing
  pageRef: host/pricing
  weight: 30
# Community tabbed menu
community:
- name: Community
  pageRef: /community/
  weight: 10
- name: Community Events
  pageRef: /community/events
  weight: 20
- name: Get Connected
  pageRef: /community/get-connected
  weight: 30
- name: Get Involved
  pageRef: /community/get-involved
  weight: 40
# Membership tabbed menu
membership:
- name: Membership
  pageRef: /support/membership
  weight: 10
- name: Membership FAQ
  pageRef: /support/membership/membership-faq
  weight: 20
- name: Current Members
  pageRef: /support/membership/member-list/
# CLDT tabbed menu
cldt:
- name: Lesson Development
  pageRef: /lesson-development
  weight: 10
- name: Lesson Development FAQ
  pageRef: /lesson-development/cldt-faq
  weight: 20

# Main menu
main:
# Main menu: About
- identifier: about-us
  name: About us
  url: "/about-us/"
  parent: null
  weight: 10
- identifier: about-the-carpentries
  name: The Carpentries
  pageRef: "/about-us/"
  parent: about-us
  weight: 10
- identifier: impact
  name: Impact
  pageRef: "/about-us/impact/"
  parent: about-us
  weight: 20
- identifier: governance
  name: Governance
  pageRef: "/about-us/governance/"
  parent: about-us
  weight: 30
- identifier: financials
  name: Financials
  pageRef: "/about-us/financials/"
  parent: about-us
  weight: 40
- identifier: team
  name: Team
  pageRef: "/about-us/team/"
  parent: about-us
  weight: 50
- identifier: careers
  name: Careers
  pageRef: "/about-us/careers/"
  parent: about-us
  weight: 60
- identifier: contact-us
  name: Contact us
  pageRef: "/about-us/contact/"
  parent: about-us
  weight: 70
# Learn Menu
- identifier: learn
  name: Learn
  url: "#"
  parent: null
  weight: 20
- identifier: workshops
  name: Workshops
  pageRef: "/workshops/"
  parent: learn
  weight: 10
- identifier: lessons
  name: Lessons
  pageRef: "/lessons/"
  parent: learn
  weight: 20
- identifier: instructor-training
  name: Instructor Training
  pageRef: "/instructor-training/"
  parent: learn
  weight: 30
- identifier: trainer-training
  name: Trainer Training
  pageRef: "/trainer-training/"
  parent: learn
  weight: 40
- identifier: lesson-development
  name: Lesson Development
  pageRef: "/lesson-development/"
  parent: learn
  weight: 50
# Volunteer menu
- identifier: volunteer
  name: Volunteer
  url: "#"
  parent: null
  weight: 30
- identifier: community
  name: Community
  url: "/community/"
  parent: volunteer
  weight: 10
- identifier: get-involved
  name: Get Involved
  url: "/community/get-involved"
  parent: volunteer
  weight: 20
- identifier: handbook
  name: Handbook
  url: "https://carpentries-beta-handbook-preview.netlify.app/"
  parent: volunteer
  weight: 30
- identifier: amy
  name: AMY
  url: "https://amy.carpentries.org/"
  parent: volunteer
  weight: 50
# Host menu
- identifier: host
  name: Host
  url: "#"
  parent: null
  weight: 40
- identifier: host-a-workshop
  name: Host a workshop
  pageRef: "/host/host-workshop/"
  parent: host
  weight: 10
- identifier: host-a-training
  name: Host a training
  url: "/host/host-training/"
  parent: host
  weight: 20
- identifier: pricing
  name: Pricing
  url: "/host/pricing/"
  parent: host
  weight: 30
# Support Menu
- identifier: support
  name: Support us
  url: "#"
  parent: null
  weight: 50
- identifier: membership
  name: Membership
  url: "/support/membership"
  parent: support
  weight: 10
- identifier: sponsorship
  name: Sponsorship
  url: "/support/sponsorship"
  parent: support
  weight: 20
- identifier: donate
  name: Donate
  url: "https://give.communityin.org/TheCarpentries?ref=ab_3YLLe3LMyx83YLLe3LMyx8"
  parent: support
  weight: 30
# Communications menu
- identifier: communications
  name: Communications
  url: "#"
  parent: null
  weight: 60
- identifier: blog
  name: Blog
  url: "/blog/"
  parent: communications
  weight: 10
- identifier: newsletter
  name: Newsletter
  pageRef: "/newsletter/"
  parent: communications
  weight: 20
- identifier: contact
  name: Contact us
  url: "/about-us/contact/"
  parent: communications
  weight: 30
# Search
- identifier: search
  name: Search
  url: '/search/'
  parent: null 
  weight: 70
footer:
# Footer menu: Menu 1 (About us)
- identifier: about-us-footer
  name: About us
  url: "/about-us/"
  parent: null
  weight: 10
- identifier: mission
  name: Our mission
  url: "/about-us/#our-mission"
  parent: about-us-footer
  weight: 20
- identifier: history
  name: Our history
  url: "/about-us/#our-history"
  parent: about-us-footer
  weight: 30
- identifier: values
  name: Our values
  url: "/about-us/#our-values"
  parent: about-us-footer
  weight: 40
# Footer menu: Menu 2
- identifier: community-footer
  name: Our community
  url: "#"
  parent: null
  weight: 20
- identifier: volunteers
  name: Our volunteers
  url: /community/
  parent: community-footer
  weight: 20
- identifier: governance
  name: Our governance
  url: "/about-us/governance/"
  parent: community-footer
  weight: 30
- identifier: get-involved
  name: Get involved
  url: "/community/get-connected/"
  parent: community-footer
  weight: 40
# Footer menu: Menu 3
- identifier: membership-footer
  name: Membership
  url: "#"
  parent: null
  weight: 30
- identifier: membership-faq
  name: Membership FAQ
  url: "/support/membership/membership-faq/"
  parent: membership-footer
  weight: 20
- identifier: current-members
  name: Current members
  url: "/support/membership/member-list/"
  parent: membership-footer
  weight: 30
- identifier: become-member
  name: Become a member
  url: "/support/membership/"
  parent: membership-footer
  weight: 40
# Footer menu: Menu 4 
- identifier: workshops-footer
  name: Workshops
  url: "#"
  parent: null
  weight: 40
- identifier: workshops-faq
  name: Workshops FAQ
  url: "/workshops/workshops-faq/"
  parent: workshops-footer
  weight: 10 
- identifier: workshops-upcoming
  name: Upcoming workshops
  url: "/workshops/upcoming-workshops/"
  parent: workshops-footer
  weight: 20
- identifier: workshops-request
  name: Request a workshop
  url: "/host/host-workshop/"
  parent: workshops-footer
  weight: 30
# Footer menu 5
- identifier: lessons-footer
  name: Lessons
  url: "#"
  parent: null
  weight: 50
- identifier: lessons-search
  name: Search lessons
  url: "/lessons/"
  parent: lessons-footer
  weight: 10
- identifier: lessons-instructor-training
  name: Instructor Training
  url: "/instructor-training/"
  parent: lessons-footer
  weight: 20
- identifier: lessons-trainer-training
  name: Trainer Training
  url: "/trainer-training/"
  parent: lessons-footer
  weight: 30
# Footer menu 6 
- identifier: lesson-development-footer
  name: Lesson Development
  url: "#"
  parent: null
  weight: 60
- identifier: cldt-footer
  name: Collaborative Lesson Development Training
  url: "#"
  parent: lesson-development-footer
  weight: 10
- indentifier: incubator-footer
  name: Carpentries Incubator
  url: "#"
  parent: lesson-development-footer
  weight: 20
- identifier: lab-footer
  name: Carpentries Lab
  url: "#"
  parent: lesson-development-footer
  weight: 30
socials:
- name: Mastodon
  url: "https://hachyderm.io/@thecarpentries"
  params:
    img: "/mastodon-logo.svg"
  weight: 10
- name: LinkedIn
  url: "https://www.linkedin.com/company/the-carpentries/"
  params:
    img: "/linkedin-logo.svg"
  weight: 20
- name: Slack
  url: "https://swc-slack-invite.herokuapp.com/"
  params:
    img: "/slack-logo.svg"
  weight: 30
- name: Github
  url: "https://github.com/carpentries"
  params:
    img: "/github-logo.svg"
  weight: 40
- name: Zenodo
  url: "https://zenodo.org/communities/carpentries/records"
  params:
    img: "/zenodo-logo.svg"
  weight: 50
- name: Youtube
  url: "https://www.youtube.com/thecarpentries"
  params:
    img: "/youtube-logo.svg"
  weight: 60

