description: The Carpentries is a fiscally sponsored project of Community Initiatives, a registered 501(c)3 non-profit organisation based in California, USA. We are a global community teaching foundational computational and data science skills to researchers in academia, industry and government.
images:
- thearpentries-opengraph.png
title: The Carpentries

git_repo: https://github.com/carpentries/new-site
handbook_url: https://docs.carpentries.org

# General email addresses

team_email: team@carpentries.org
membership_email: membership@carpentries.org
workshops_email: workshops@carpentrires.org
instructor_training_email: instructor.training@carpentries.org
coc_email: coc@carpentries.org

# Social media platforms

youtube: https://www.youtube.com/thecarpentries
mastodon: https://hachyderm.io/@thecarpentries

# AMY links
amy_base: https://amy.carpentries.org
amy_workshop_landing: https://amy.carpentries.org/forms/workshop/
amy_req_cow: https://amy.carpentries.org/forms/request_workshop/
amy_reg_sow: https://amy.carpentries.org/forms/self-organised/
amy_training: https://amy.carpentries.org/forms/request_training/

# Instructor training links
checkout_instructions: https://carpentries.github.io/instructor-training/checkout.html
footer_overview_text: "The Carpentries is a fiscally sponsored project of Community Initiatives, a registered 501(c)3 non-profit organisation based in California, USA. We are a global community teaching foundational computational and data science skills to researchers in academia, industry and government."
footer_donate_url: "#"